version: "3.8"

networks:
  docker-macvlan0:
    external: true

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/tcp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443/443/tcp"
    networks:
      docker-macvlan0:
        ipv4_address: ${PIHOLE_IP}
    labels:
      caddy: "pihole.local"
      caddy.rewrite: "* /target{admin}"
      caddy.reverse_proxy: "{{upstreams 443}}"
    environment:
      TZ: ${TZ}
    volumes:
      - ${ROOT}/config/etc-pihole:/etc/pihole
      - ${ROOT}/config/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
