version: "3"

networks:
  pihole-macvlan0:
    driver: macvlan
    driver_opts:
      parent: ${PI_HOLE_INTERFACE}
    ipam:
      config:
        - subnet: ${PI_HOLE_SUBNET}
          gateway: ${PI_HOLE_GATEWAY}
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/tcp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      pihole-macvlan0:
        ipv4_address: ${PI_HOLE_IP}
    environment:
      TZ: ${TZ}
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
