version: "3.8"

networks:
  docker-macvlan0:
    external: true

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    networks:
      docker-macvlan0:
        ipv4_address: ${HOMEPAGE_IP}
    labels:
      caddy: "homepage.local"
      caddy.reverse_proxy: "{{upstreams 3000}}"
    volumes:
      - ${ROOT}/config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
