version: "3.8"

networks:
  docker-macvlan0:
    external: true

services:
  dump1090:
    container_name: dump1090
    restart: unless-stopped
    image: "jraviles/dump1090:latest"
    networks:
      docker-macvlan0:
        ipv4_address: ${DUMP1090_IP}
    devices:
      - /dev/dvb:/dev/dvb
    privileged: true

  adsbexchange:
    container_name: adsbx
    image: ghcr.io/sdr-enthusiasts/docker-adsbexchange:latest
    restart: unless-stopped
    networks:
      - docker-macvlan0
    links:
      - "dump1090:decoder"
    environment:
      - TZ=${TZ}
      - BEASTHOST=dump1090
      - LAT=${LAT}
      - LONG=${LONG}
      - ALT=${ALT}
      - SITENAME=${SITENAME}
      - UUID=${UUID}
    tmpfs:
      - /run:rw,nosuid,nodev,exec,relatime,size=64M,uid=1000,gid=1000
