version: "3.8"

networks:
  docker-macvlan0:
    external: true

services:
  sdr-server:
    container_name: sdr-server
    restart: unless-stopped
    build:
      context: "."
      dockerfile: "Dockerfile"
    devices:
      - /dev/dvb:/dev/dvb
    privileged: true
    ports:
      - "1234:1234"
    networks:
      docker-macvlan0:
        ipv4_address: ${SDR_IP}
