FROM nginx:latest

COPY nginx/nginx.conf /etc/nginx/
COPY nginx/nginxconfig.txt /etc/nginx/
COPY nginx/nginxconfig.io/* /etc/nginx/nginxconfig.io/
COPY nginx/sites-available/* /etc/nginx/sites-available/
