version: "3.4"

networks:
  docker-macvlan0:
    external: true

services:
  nginx:
    container_name: nginx
    build:
      context: "."
      dockerfile: "Dockerfile"
    networks:
      docker-macvlan0:
        ipv4_address: ${NGINX_IP}
