version: "3.4"

networks:
  docker-macvlan0:
    external: true

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      docker-macvlan0:
        ipv4_address: ${PORTAINER_IP}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${ROOT}/config/portainer/portainer-data:/data
